baseURL = 'https://example.org/'
languageCode = 'ja-JP'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  author = 'Blog autohr name'
  authorImage = 'author.jpg'
  authorDescription = 'Blog author description.'
  customCss = []
  customJs = []

[params.sideBar]
  showAuthor = true
  showSocial = true
  showTags = true

[params.social]
  website = 'https://example.com/my_url'
  email = 'my_email@example.com'
  github = 'github'
  twitter = 'twitter'
  bluesky = 'bsky.app'
  instagram = 'instagram'
  facebook = 'https://www.facebook.com/facebook'
  youtube = 'https://www.youtube.com/user/YouTubeJapan'

[params.footer]
  copyrightName = 'example.com'
  copyrightUrl = 'https://example.com'
  sinceYear = 2020
