baseURL = 'https://example.org/'
languageCode = 'ja-JP'
title = 'My New Hugo Site'

[[menus.main]]
name = 'Home'
pageRef = '/'
weight = 10

[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 20

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 30

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"

[params]
  author = 'Blog autohr name'
  authorImage = 'author.jpg'
  authorDescription = 'Blog author description.'

  [params.sideBar]
    showAuthor = true
